- name: Add Microsoft key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VSCode repo
  copy:
    content: |
       [code]
       name=Visual Studio Code
       baseurl=https://packages.microsoft.com/yumrepos/vscode
       enabled=1
       gpgcheck=1
       gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/vscode.repo

- name: Install VSCode
  dnf:
    name: code

- name: Import VSCode settings
  become: yes
  become_user: "{{ current_user }}"
  copy:
    src: vscode/.config/Code/User
    dest: ~/.config/Code
    directory_mode: yes


